[2022-05-12 15:05:01,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T15:05:00.727531+00:00 [queued]>
[2022-05-12 15:05:01,308] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T15:05:00.727531+00:00 [queued]>
[2022-05-12 15:05:01,308] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:05:01,309] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 15:05:01,310] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 15:05:01,320] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-12 15:05:00.727531+00:00
[2022-05-12 15:05:01,325] {standard_task_runner.py:52} INFO - Started process 2921 to run task
[2022-05-12 15:05:01,332] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-12T15:05:00.727531+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmp3o90xnml', '--error-file', '/tmp/tmp4d_tot76']
[2022-05-12 15:05:01,336] {standard_task_runner.py:80} INFO - Job 86: Subtask producer_twitter_data
[2022-05-12 15:05:01,428] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-12T15:05:00.727531+00:00 [running]> on host 78a2fc18e687
[2022-05-12 15:05:01,808] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T15:05:00.727531+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T15:05:00.727531+00:00
[2022-05-12 15:05:01,811] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 15:05:01,813] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/producer_tweets.py']
[2022-05-12 15:05:01,839] {subprocess.py:85} INFO - Output:
[2022-05-12 15:05:02,325] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 15:05:02,326] {subprocess.py:92} INFO -   File "/opt/***/dags/producer_tweets.py", line 21, in <module>
[2022-05-12 15:05:02,327] {subprocess.py:92} INFO -     producer = KafkaProducer(bootstrap_servers='localhost:9092')
[2022-05-12 15:05:02,328] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2022-05-12 15:05:02,329] {subprocess.py:92} INFO -     **self.config)
[2022-05-12 15:05:02,331] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
[2022-05-12 15:05:02,332] {subprocess.py:92} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2022-05-12 15:05:02,334] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
[2022-05-12 15:05:02,335] {subprocess.py:92} INFO -     raise Errors.NoBrokersAvailable()
[2022-05-12 15:05:02,336] {subprocess.py:92} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-05-12 15:05:02,343] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 15:05:02,355] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 15:05:02,359] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220512T150500, start_date=20220512T150501, end_date=20220512T150502
[2022-05-12 15:05:02,368] {standard_task_runner.py:97} ERROR - Failed to execute job 86 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 2921)
[2022-05-12 15:05:02,393] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 15:05:02,414] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
