[2022-05-12 10:47:10,599] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T10:47:09.591394+00:00 [queued]>
[2022-05-12 10:47:10,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T10:47:09.591394+00:00 [queued]>
[2022-05-12 10:47:10,609] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 10:47:10,611] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 10:47:10,613] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 10:47:10,624] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): consumer_twitter_data> on 2022-05-12 10:47:09.591394+00:00
[2022-05-12 10:47:10,629] {standard_task_runner.py:52} INFO - Started process 377 to run task
[2022-05-12 10:47:10,631] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'consumer_twitter_data', 'manual__2022-05-12T10:47:09.591394+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpv0k80nvf', '--error-file', '/tmp/tmp4t8mtdv3']
[2022-05-12 10:47:10,633] {standard_task_runner.py:80} INFO - Job 45: Subtask consumer_twitter_data
[2022-05-12 10:47:10,677] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.consumer_twitter_data manual__2022-05-12T10:47:09.591394+00:00 [running]> on host d4b54e84cd08
[2022-05-12 10:47:10,899] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=consumer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T10:47:09.591394+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T10:47:09.591394+00:00
[2022-05-12 10:47:10,900] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 10:47:10,902] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/consumer_tweets.py']
[2022-05-12 10:47:10,909] {subprocess.py:85} INFO - Output:
[2022-05-12 10:47:11,204] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64//bin/java: No such file or directory
[2022-05-12 10:47:11,205] {subprocess.py:92} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2022-05-12 10:47:11,300] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-12 10:47:11,301] {subprocess.py:92} INFO -   File "/opt/***/dags/consumer_tweets.py", line 39, in <module>
[2022-05-12 10:47:11,301] {subprocess.py:92} INFO -     .config("spark.streaming.stopGracefullyOnShutdown", "true") \
[2022-05-12 10:47:11,302] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
[2022-05-12 10:47:11,303] {subprocess.py:92} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2022-05-12 10:47:11,304] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 392, in getOrCreate
[2022-05-12 10:47:11,305] {subprocess.py:92} INFO -     SparkContext(conf=conf or SparkConf())
[2022-05-12 10:47:11,306] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 144, in __init__
[2022-05-12 10:47:11,307] {subprocess.py:92} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2022-05-12 10:47:11,309] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/context.py", line 339, in _ensure_initialized
[2022-05-12 10:47:11,309] {subprocess.py:92} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2022-05-12 10:47:11,310] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
[2022-05-12 10:47:11,312] {subprocess.py:92} INFO -     raise RuntimeError("Java gateway process exited before sending its port number")
[2022-05-12 10:47:11,313] {subprocess.py:92} INFO - RuntimeError: Java gateway process exited before sending its port number
[2022-05-12 10:47:11,325] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 10:47:11,335] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 10:47:11,338] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=consumer_twitter_data, execution_date=20220512T104709, start_date=20220512T104710, end_date=20220512T104711
[2022-05-12 10:47:11,346] {standard_task_runner.py:97} ERROR - Failed to execute job 45 for task consumer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 377)
[2022-05-12 10:47:11,374] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 10:47:11,473] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
